### ISSUE TITLE
[Fix-Suggestion] Dynamite/TNT Explosions Destroys Dank Storage

### ISSUE THREAD

**Issue by 0xebjc** [Tfarcenim/Dank-Storage#136]
recommend changing block properties, and add explosion resistance 18,000,000, because blocks are being destroyed by explosions and only returning air and no dank storage block/item.

**Comment by Tfarcenim** [comment]
It's already has a 5x higher blast resistance than stone (150).  I'll increase the blast resistance a little bit, but it won't be 18 million because it isn't bedrock and shouldn't be used as such.  If people are still blowing it up, then frankly they deserve it.

Returning air/nothing is normal for high powered explosions other than tnt which drops 100% of what it breaks.
No, I will not be creating a release just for this.
