### ISSUE TITLE
Inventory Mess With T.Con Table & Mass Duplication with MineColonies

### ISSUE THREAD

**Issue by ArkavianX** [Tfarcenim/Dank-Storage#152]
Found buggy/odd behavior with Dank Null, Tinkers Construct and MineColonies.

When you place a T.Con Crafting table with a docked L6 Null, the crafting table tries to connect to the null, and breaks the players inventory and fails to display anything in the Null, but does recognize that something is connected. 

The same bug is worse with MineColonies and initially posted there... 

https://github.com/ldtteam/minecolonies/issues/7867 

The issue can massively duplicate materials.

MC 1.16.5 The bug occurs in both ATM 6 Standard & Sky mod packs.

**Comment by Random832** [comment]
I did some investigation in an instance with only Dank Storage and Tinker's Construct. The Dank appears to be mapped to the top rows of the player inventory grid within the crafting station GUI rather than the side inventory [this is easiest to test with a Dank 1 - in this case, the 3 main rows of player inventory are shifted down one row, and the top row alone is mapped to the dank]. This may explain why the OP seemed to think the problem required higher tiers of Dank, since those have enough slots to completely push the player inventory out of the gui slots.

At a guess, I suspect the client side dank dock tile entity has no inventory slots, while the server side one is normal. The crafting station accesses the client side item handler capability for various purposes in the client side GUI container, including enumerating the slots and using their contents [via IItemHandlerModifiable] as backing storage for the GUI slots.

**Comment by Tfarcenim** [comment]
Added a workaround for now, wasn't expecting mods to access the clientside IItemHandler so I gave it a dummy one with the correct slots.
