### ISSUE TITLE
[1.19.x] Inventory Sorter is messing things.

### ISSUE THREAD

**Issue by Bass2style** [Tfarcenim/Dank-Storage#181]
Hello,

i found a bug when missclicking in a Dank when InventorySorter is in the pack.
when you "sort" the inventory, InventorySorter is making stacks of the first item in all slots of the dank, wiping everything else that was in it.
it's a report for 1.19.2, but i think any version of MC with both mods in a pack are probably affected.

idk who of the two mods are able to ignore the other in this circumstance, but both should not interract that way.
i'm reporting/suggestin this on both git, because it's a bit annoying, i lost a ton of stuff because a missclick. xD so if one of the two can make a quickfix for this, it could be cool.

video to show the behavior : https://youtu.be/HvGnUgbLuEg (sorry for the background music. xD)

have a nice day.

**Comment by Tfarcenim** [comment]
This is up to them to fix, it's been a problem ever since this mod was first created as almost every sorting mod assumes that there will never be more than an item's max stack size in a slot which is their fault.

I don't want to blacklist it on my end, because if they ever fix the bug, then it wouldn't make sense to prevent it from sorting as there isn't anything special other than the stacking capabilities.

As for what you can do on your end, I suggest adding this mod's containers to the blacklist for now.

**Comment by Bass2style** [comment]
do you know what value to set in the blacklist ? because i found the config file, but idk what to fill in it. xD

waiting for CPW treating my report, but i understand your opinion, i also think it's easyer to CPW to fix this.
