### ISSUE TITLE
interesting reason

### ISSUE THREAD

**Issue by Xplodin** [Tfarcenim/Dank-Storage#275]
![image](https://github.com/user-attachments/assets/ddc864d9-d319-4cf5-813d-5f1dcb6476b6)

**Comment by Tfarcenim** [comment]
I'll add a proper reason when I update the mod again, but long story short, I've had too many issues with connector enabled mods breaking mine so now I have that on any high complexity project where issues are hard to track down.

I have limited time and every hour I spend on a connector related issue is time I'm not spending on commissions, actually important bugfixes and general maintenance.

Needless to say this will not change, and if anything else of similar popularity like Optifine/Optifabric starts showing up in reports they'll be added to the list too.

This notice also applies to my fabric mods, I do not support running them via connector and will instantly close any issue involving it.

**Comment by Xplodin** [comment]
does this really call for making it completely crash for others though?
I understand the frustration for connector related issues with your mod. But I think just saying no support for connector on the mod pages is enough. I just wanna use both mods in a pack whether its supported or not supported

**Comment by Tfarcenim** [comment]
> does this really call for making it completely crash for others though?

The point is to reveal the problem early rather than letting it load and then it secretly corrupts because a fabric mod broke something.  Or it crashes anyways, but they don't know why and they come to me with a 300 long modlist expecting me to fix it.

>  But I think just saying no support for connector on the mod pages is enough.

I tried that, but most users don't listen or file reports if something goes wrong.  Or they'll look at a warning popup, ignore it, and then try to get support anyways or blame me for their world crashing.

This makes the issue more clear.

**Comment by Xplodin** [comment]
is it possible for maybe a config to override the crash but a clear message that support is not given for enabling it to load?

**Comment by Tfarcenim** [comment]
Yes, dependency overrides can disable it, but there will still be warnings.

**Comment by milkev** [comment]
doubt ill change your mind on this, but issues related to connector should be reported to connector or redirected to connector. Individual mod authors are not expected to fix these issues, and 99.99% of the time its outside of the indivual mod authors capabilities anyway.

marking connector as completely incompatable because some mods cause issues is (in my opinion) a frankly childish and extremely hostile way of "solving" the issue at hand.

**Comment by Xplodin** [comment]
I agree to both points here, it can be annoying to deal with connector and getting connector related issues in the wrong repo. But its definitely a bit extreme, I had to use the fabric dank storage just to bypass the forge message. Dependency overrides only work with fabric mods
